version: '3.8'

###############################################################################
#                             NETWORKS                                        #
#/////////////////////////////////////////////////////////////////////////////#

networks:
  transcendence_network:
    driver: bridge

###############################################################################
#                             VOLUMES                                         #
#/////////////////////////////////////////////////////////////////////////////#

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./../data/postgres # srcs/requirements/postgres folder.
  pgadmin4_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./../data/pgadmin4 # srcs/requirements/pgadmin4 folder.
  backend_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./../data/backend # srcs/requirements/backend folder.
  frontend_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./../data/frontend # srcs/requirements/frontend folder.
  # Buraya da sonraki datalarin konumlari eklenebilinir.

###############################################################################
#                             SERVICES                                        #
#/////////////////////////////////////////////////////////////////////////////#
services:
  # # _____nest-js____ #
  # nest-js: # For 'Web Server'.
  #   container_name: nest-js # PDF asks us to create it with this name.
  #   build: ./requirements/nest-js/ # Container's 'Dockerfile' path location for run this file.
  #   env_file: .env
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #     - ./requirements/nest-js:/app
  #   networks:
  #     - transcendence_network
  #   restart: always
  #   ports:
  #     - 3000:3000 # Local port / Exported port. nestjs's default port(3000).
  #   # depends_on:
  #   # progress: plain
  # # ________________ #
  # ___PostgreSQL___ # OK
  postgres:
    image: postgres:16.0-alpine3.18
    env_file:
      - ./envFiles/postgres.env
      # - ./requirements/postgres/.env
    volumes:
      - ./requirements/postgres:/app
    networks:
      - transcendence_network
    restart: always
    ports:
      - 5432:5432 # Local port / Exported port. postgres's default port(5432).
    # depends_on:
    # progress: plain
  # ________________ #
  # ____pgadmin4____ #
  pgadmin4:
    image: dpage/pgadmin4:7.4
    env_file:
      - ./envFiles/pgadmin4.env
    volumes:
      - ./requirements/pgadmin4:/app
    networks:
      - transcendence_network
    restart: always
    ports:
      - 80:80 # Local port / Exported port.
      # - 5432:5432 # Local port / Exported port.
    # depends_on:
    # progress: plain
  # ________________ #