# # FROM postgres:alpine:lastest
# FROM postgres:16.0-alpine

# LABEL author="gsever and akaraca"
# LABEL description="Postgres Image for ft_transcendence"
# LABEL version="1.0"

# # COPY *.sql /docker-entrypoint-initdb.d/