# LINK: https://hub.docker.com/_/node
# LINK: https://github.com/nodejs/docker-node/blob/ce9bfa282b62ece538fef25b954ade4401a7c8c7/20/alpine3.18/Dockerfile
FROM node:20.7.0-alpine3.18

# RUN apk update && \
# 	apk add --no-cache \
# 	&& rm -rf /var/cache/apk/*